Update packages related to requests
Pegleg Promenade and Shipyard should all use same versions of
packages when able.  Requests currently is giving a warning
in Pegleg:
ERROR: deckhand 0.0.1.dev657 has requirement urllib3==1.24, but
you'll have urllib3 1.24.3 which is incompatible.

Change-Id: I9f21203b4109e7542a952d68c7a6ffcdb2653026