Update DeckHand Dag/Operator
We are facing an issue with the Deckhand Client [0]
and will need to skip the 'shipyard_retrieve_rendered_doc'
for the time being while we wait for a resolution for [0].
Note that 'shipyard_retrieve_rendered_doc' is not really needed
for actual deployment to work and was introduced as part of
the Shipyard-270 story.

Also fix bugs with the deckhand operator [2] after [1] was merged.

[0] https://github.com/att-comdev/deckhand/issues/18
[1] https://review.gerrithub.io/#/c/395922/

[2]

Error 1:

INFO - Subtask:   File "/usr/local/airflow/plugins/deckhand_operator.py", line 132, in execute
INFO - Subtask:     revision_id=revision_id)
INFO - Subtask: TypeError: keystone_token_get() got an unexpected keyword argument 'revision_id'

Error 2:

INFO - Subtask:   File "/usr/local/airflow/plugins/deckhand_operator.py", line 219, in deckhand_validate_site
INFO - Subtask:     context['revision_id'])
INFO - Subtask: KeyError: 'revision_id'

Change-Id: I03ce29b24d1b3ff6148f2eb4970614b1389a58a6