Bug Fix - DeckHand Operator
The following error [0] is seen in the Airflow Web pod after
[1] was merged. This prevents the airflow services from starting
properly.

This patch set is meant to fix that problem.

[0] Error messages

[2018-01-30 07:34:53,499] {plugins_manager.py:91} ERROR - cannot import name 'deckhand_client'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/airflow/plugins_manager.py", line 80, in <module>
    m = imp.load_source(namespace, filepath)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/airflow/plugins/deckhand_operator.py", line 28, in <module>
    from deckhand.client import deckhand_client
ImportError: cannot import name 'deckhand_client'
[2018-01-30 07:34:53,505] {plugins_manager.py:92} ERROR - Failed to import plugin /usr/local/airflow/plugins/deckhand_operator.py

[1] https://review.gerrithub.io/#/c/395922/

Change-Id: I84976e95f77968ad6a74490843f48f93b7d478e7