[Fix] Update dag name in dag_names dag
A bug was introduced while trying to rebase and resolve the
merge conflicts in [0]. This led to errors [1] while executing
action workflow with Shipyard.

This patch set will fix the bug

[0] https://review.gerrithub.io/#/c/att-comdev/shipyard/+/408289/
[1] Errors seen in Airflow Web

[2018-04-26 06:50:55,991] {{models.py:288}} ERROR - Failed to import: /usr/local/airflow/dags/deploy_site.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/airflow/models.py", line 285, in process_file
    m = imp.load_source(mod_name, filepath)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/airflow/dags/deploy_site.py", line 19, in <module>
    from common_step_factory import CommonStepFactory
  File "/usr/local/airflow/dags/common_step_factory.py", line 32, in <module>
    class CommonStepFactory(object):
  File "/usr/local/airflow/dags/common_step_factory.py", line 92, in CommonStepFactory
    def get_get_rendered_doc(self, task_id=dn.GET_RENDERED_DOC):
AttributeError: module 'dag_names' has no attribute 'GET_RENDERED_DOC'

Change-Id: Ib4e26f4acc951bc460ece5d51cea8e0acfdc73d8