Bug Fix for REST API Plugin
The following error was encountered

NameError: name 'filter_loading_messages_in_cli_response' is not defined

It is noted that some variables were missing in the codes.  This
patch is to address that.

Change-Id: Id5141765d0b06e48fcf4ae3f1ca0410766c3216c